services:
  - type: web
    name: tall-ui-mcp-server
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start:http
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000